[[npc]]
type = "CREATURE"
name = "Goblin"
maxHealth = 100
damage = 15

[[npc]]
type = "CREATURE"
name = "Squeleton"
maxHealth = 80
damage = 18

[[npc]]
type = "CREATURE"
name = "Zombie"
maxHealth = 130
damage = 11

[[npc]]
type = "CREATURE"
name = "Spider"
maxHealth = 70
damage = 13

[[npc]]
type = "CREATURE"
name = "Orc"
maxHealth = 170
damage = 20

[[npc]]
type = "CREATURE"
name = "Golem"
maxHealth = 200
damage = 22
