#ifndef ARGENTUM_EDITOR_EDITOR_CONSTANTS_H
#define ARGENTUM_EDITOR_EDITOR_CONSTANTS_H

#define CELL_DISPLAY_SIZE 64
#define TARGET_CELL_SCREEN_PX 32

#ifndef EDITOR_SAVE_MAP_PATH
#define EDITOR_SAVE_MAP_PATH "../server/assets/maps"
#endif

#ifndef EDITOR_TEMPLATES_PATH
#define EDITOR_TEMPLATES_PATH "assets/templates"
#endif

#ifndef EDITOR_TEMPLATES_CITIES_PATH
#define EDITOR_TEMPLATES_CITIES_PATH EDITOR_TEMPLATES_PATH "/cities"
#endif

#ifndef EDITOR_TEMPLATES_BIOMES_PATH
#define EDITOR_TEMPLATES_BIOMES_PATH EDITOR_TEMPLATES_PATH "/biomes"
#endif

#ifndef EDITOR_TEMPLATES_OBSTACLES_PATH
#define EDITOR_TEMPLATES_OBSTACLES_PATH EDITOR_TEMPLATES_PATH "/obstacles"
#endif

#ifndef EDITOR_TEMPLATES_ENTRIES_PATH
#define EDITOR_TEMPLATES_ENTRIES_PATH EDITOR_TEMPLATES_PATH "/entries"
#endif

#ifndef EDITOR_TEMPLATES_WALLS_PATH
#define EDITOR_TEMPLATES_WALLS_PATH EDITOR_TEMPLATES_PATH "/walls"
#endif

#ifndef EDITOR_TEMPLATES_EXITS_PATH
#define EDITOR_TEMPLATES_EXITS_PATH EDITOR_TEMPLATES_PATH "/exits"
#endif

#ifndef EDITOR_TEMPLATES_FLOORS_PATH
#define EDITOR_TEMPLATES_FLOORS_PATH EDITOR_TEMPLATES_PATH "/tiles"
#endif

#ifndef EDITOR_ASSETS_IMAGES_PATH
#define EDITOR_ASSETS_IMAGES_PATH "assets/images"
#endif

#ifndef EDITOR_ASSETS_UI_TEXTURES_PATH
#define EDITOR_ASSETS_UI_TEXTURES_PATH "assets/ui_textures"
#endif

#define SAVE_MAP EDITOR_SAVE_MAP_PATH
#define TEMPLATES_PATH EDITOR_TEMPLATES_PATH
#define TEMPLATES_CITIES_PATH EDITOR_TEMPLATES_CITIES_PATH
#define TEMPLATES_BIOMES_PATH EDITOR_TEMPLATES_BIOMES_PATH
#define TEMPLATES_OBSTACLES_PATH EDITOR_TEMPLATES_OBSTACLES_PATH
#define TEMPLATES_ENTRIES_PATH EDITOR_TEMPLATES_ENTRIES_PATH
#define TEMPLATES_WALLS_PATH EDITOR_TEMPLATES_WALLS_PATH
#define TEMPLATES_EXITS_PATH EDITOR_TEMPLATES_EXITS_PATH
#define TEMPLATES_FLOORS_PATH EDITOR_TEMPLATES_FLOORS_PATH
#define ASSETS_IMAGES_PATH EDITOR_ASSETS_IMAGES_PATH
#define ASSETS_UI_TEXTURES_PATH EDITOR_ASSETS_UI_TEXTURES_PATH
#define PLAYER_SPAWN_TEXTURE ASSETS_UI_TEXTURES_PATH "/player_spawn.png"

#define DATA_TYPE (Qt::UserRole + 1)
#define DATA_ID (Qt::UserRole + 2)
#define DATA_SUBTYPE (Qt::UserRole + 3)
#define DATA_WIDTH (Qt::UserRole + 4)
#define DATA_HEIGHT (Qt::UserRole + 5)
#define DATA_TEXTURE_ANCHOR (Qt::UserRole + 7)

#define PLAYER_SPAWN_TYPE "player_spawn"
#define OBSTACLE_TYPE "obstacle"
#define CITY_ZONE_TYPE "city_zone"
#define BIOME_ZONE_TYPE "biome_zone"
#define ENTRY_TYPE "entry"
#define WALL_TYPE "wall"
#define EXIT_TYPE "exit"
#define FLOOR_TYPE "floor"

#define ZONE_TYPE_CITY "city"
#define ZONE_TYPE_BIOME "biome"

#define DATA_ENVIRONMENT_ID (Qt::UserRole + 6)

#define MIN_ZOOM 0.05
#define MAX_ZOOM 2.0
#define ZOOM_SCALE 0.05
#define INITIAL_ZOOM 1.0

#define CREATURE_SLIDER_MIN 0
#define CREATURE_SLIDER_MAX 50
#define CREATURE_SLIDER_DEFAULT 0
#define CREATURE_VALUE_LABEL_WIDTH 28

inline constexpr int ENVIRONMENT_SIZE = 30;

// Z order de los elementos del mapa (de abajo hacia arriba)
#define Z_BACKGROUND -2.0
#define Z_ENV_FLOOR -1.8
#define Z_BIOME_TEXTURE -1.7
#define Z_ENV_EXTERIOR -1.6
#define Z_FLOOR_MODIFIER -1.4
#define Z_GRID -1.0
#define Z_BIOME_ZONE 1.0
#define Z_CITY_ZONE 2.0
#define Z_OBSTACLE 3.0
#define Z_ENTRY 3.0
#define Z_PLAYER_SPAWN 3.0
#define Z_WALL 3.0
#define Z_EXIT 3.0
#define Z_ZONE_PREVIEW 5.0

#endif
