[race.human]
constitution = 10
force = 8
intelligence = 6
FRaceHealth = 15.0
FRaceRecovery = 15.0
FRaceMana = 10.0

[race.elf]
constitution = 5
force = 5
intelligence = 10
FRaceHealth = 8.0
FRaceRecovery = 20.0
FRaceMana = 15.0

[race.dwarf]
constitution = 14
force = 12
intelligence = 4
FRaceHealth = 20.0
FRaceRecovery = 10.0
FRaceMana = 5.0

[race.gnome]
constitution = 5
force = 5
intelligence = 8
FRaceHealth = 6.0
FRaceRecovery = 18.0
FRaceMana = 13.0

[class.mage]
FClassHealth = 13.0
FClassMana = 15.0
FClassMeditation = 20.0

[class.cleric]
FClassHealth = 10.0
FClassMana = 13.0
FClassMeditation = 15.0

[class.champion]
FClassHealth = 18.0
FClassMana = 11.0
FClassMeditation = 10.0

[class.warrior]
FClassHealth = 20.0
FClassMana = 0.0
FClassMeditation = 0.0
