[[item]]
id = 1
name = "sword"
type = "WEAPON"
distance = false
minDamage = 2
maxDamage = 5

[[item]]
id = 2
name = "axe"
type = "WEAPON"
distance = false
minDamage = 4
maxDamage = 5

[[item]]
id = 3
name = "hammer"
type = "WEAPON"
distance = true
minDamage = 1
maxDamage = 9

[[item]]
id = 4
name = "ash staff"
type = "MAGIC"
distance = true
minDamage = 2
maxDamage = 4
manaCost = 50

[[item]]
id = 5
name = "elven flute"
type = "HEAL"
distance = true
healthRestore = 50
manaCost = 200

[[item]]
id = 6
name = "root staff"
type = "MAGIC"
distance = true
minDamage = 4
maxDamage = 8
manaCost = 150

[[item]]
id = 7
name = "socketed staff"
type = "MAGIC"
distance = true
minDamage = 8
maxDamage = 20
manaCost = 250

[[item]]
id = 8
name = "simple bow"
type = "WEAPON"
distance = true
minDamage = 1
maxDamage = 4

[[item]]
id = 9
name = "composite bow"
type = "WEAPON"
distance = true
minDamage = 4
maxDamage = 16

[[item]]
id = 10
name = "leather armor"
type = "ARMOR"
minDefense = 2
maxDefense = 6

[[item]]
id = 11
name = "plate armor"
type = "ARMOR"
minDefense = 15
maxDefense = 30

[[item]]
id = 12
name = "blue tunic"
type = "ARMOR"
minDefense = 6
maxDefense = 10

[[item]]
id = 13
name = "hood"
type = "HELMET"
minDefense = 1
maxDefense = 4

[[item]]
id = 14
name = "iron helmet"
type = "HELMET"
minDefense = 4
maxDefense = 8

[[item]]
id = 15
name = "turtle shield"
type = "SHIELD"
minDefense = 1
maxDefense = 2

[[item]]
id = 16
name = "iron shield"
type = "SHIELD"
minDefense = 1
maxDefense = 4

[[item]]
id = 17
name = "wizard hat"
type = "HELMET"
minDefense = 4
maxDefense = 12

[[item]]
id = 18
name = "health potion"
type = "HEALTH_POTION"
healthRestore = 50

[[item]]
id = 19
name = "mana potion"
type = "MANA_POTION"
manaRestore = 50
